# Generated by Django 5.1.2 on 2024-11-03 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aircraft', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personel',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personel', to='aircraft.team'),
        ),
        migrations.AddField(
            model_name='part',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='aircraft.team'),
        ),
        migrations.AlterUniqueTogether(
            name='aircraftpart',
            unique_together={('aircraft', 'part')},
        ),
    ]
