# Generated by Django 5.1.2 on 2024-11-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personel',
            name='email',
        ),
        migrations.AddField(
            model_name='personel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personel',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
