# Generated by Django 5.1.2 on 2024-11-05 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0003_remove_personel_email_personel_name_personel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_parts', to='aircraft.aircraft'),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='aircraft.team'),
        ),
    ]
